-- DDL: Create Table
CREATE TABLE DEPARTMENT 
(
    DEPT_ID    NUMBER(4,0) PRIMARY KEY,
    DEPT_NAME  VARCHAR2(50) NOT NULL,
    LOCATION   VARCHAR2(50)
);

-- Insert Dummy Data
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (10, 'Human Resources', 'New York');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (20, 'Finance', 'Chicago');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (30, 'IT', 'San Francisco');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (40, 'Marketing', 'Los Angeles');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (50, 'Sales', 'Boston');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (60, 'Customer Support', 'Dallas');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (70, 'Research & Development', 'Seattle');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (80, 'Legal', 'Washington DC');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (90, 'Administration', 'Houston');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (100, 'Procurement', 'Denver');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (110, 'Finance', 'Howard');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (120, 'Supply Chain', 'Ronin');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, LOCATION) VALUES (100, 'Inventory Specialist', 'Evelin adams');

-- Commit changes
COMMIT;
