-- DDL: Create Employee Table
CREATE TABLE EMPLOYEE 
(
    EMP_ID     NUMBER(6,0) PRIMARY KEY,
    EMP_NAME   VARCHAR2(100) NOT NULL,
    JOB_TITLE  VARCHAR2(50),
    SALARY     NUMBER(10,2),
    DEPT_ID    NUMBER(4,0),
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);

-- Insert Dummy Data
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOB_TITLE, SALARY, DEPT_ID) 
VALUES (1001, 'Alice Johnson', 'HR Manager', 75000, 10);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOB_TITLE, SALARY, DEPT_ID) 
VALUES (1002, 'Bob Smith', 'Financial Analyst', 68000, 20);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOB_TITLE, SALARY, DEPT_ID) 
VALUES (1003, 'Charlie Brown', 'Software Engineer', 85000, 30);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOB_TITLE, SALARY, DEPT_ID) 
VALUES (1004, 'Diana Miller', 'Marketing Executive', 60000, 40);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOB_TITLE, SALARY, DEPT_ID) 
VALUES (1005, 'Edward Davis', 'Sales Manager', 72000, 50);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOB_TITLE, SALARY, DEPT_ID) 
VALUES (1006, 'Fiona Wilson', 'Support Specialist', 50000, 60);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOB_TITLE, SALARY, DEPT_ID) 
VALUES (1007, 'George Thomas', 'Research Scientist', 95000, 70);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOB_TITLE, SALARY, DEPT_ID) 
VALUES (1008, 'Hannah White', 'Legal Advisor', 88000, 80);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOB_TITLE, SALARY, DEPT_ID) 
VALUES (1009, 'Ian Clark', 'Admin Officer', 52000, 90);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOB_TITLE, SALARY, DEPT_ID) 
VALUES (1010, 'Julia Lewis', 'Procurement Lead', 64000, 100);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOB_TITLE, SALARY, DEPT_ID) 
VALUES ('CICD', 'Levi Adams', 'Distribution', 60000, 110);


-- Commit changes
COMMIT;
