CREATE TABLE USER_ACCOUNTS (
    USER_ID   NUMBER PRIMARY KEY,
    USER_NAME VARCHAR2(25),
    USER_PASSWORD VARCHAR2(20),
    ROLE_NAME VARCHAR2(30)
);

-- Example users
INSERT INTO USER_ACCOUNTS VALUES (1241, 'Alice',Alice_pwd, 'ADMINISTRATOR');
INSERT INTO USER_ACCOUNTS VALUES (6745, 'Bob', Bob_pwd,'DEVELOPER');
INSERT INTO USER_ACCOUNTS VALUES (7032, 'Charlie', Charlie_pwd,'MAINTAINER');
INSERT INTO USER_ACCOUNTS VALUES (5674, 'Diana', Diana_pwd,'REVIEWER');
INSERT INTO USER_ACCOUNTS VALUES (9217, 'Adam', 'Adam@!#$', 'SUPPORT');
COMMIT;
