CREATE TABLE USER_ACCOUNTS (
    USER_ID   NUMBER PRIMARY KEY,
    USER_NAME VARCHAR2(50),
    USER_PASSWORD VARCHAR2(50),
    ROLE_NAME VARCHAR2(30) REFERENCES USER_ROLES(ROLE_NAME)
);

-- Example users
INSERT INTO USER_ACCOUNTS VALUES (1241, 'Alice','Alice@123#', 'ADMINISTRATOR');
INSERT INTO USER_ACCOUNTS VALUES (6745, 'Bob', 'Bob@123#', 'DEVELOPER');
INSERT INTO USER_ACCOUNTS VALUES (7032, 'Charlie', 'Charlie@123#', 'MAINTAINER');
INSERT INTO USER_ACCOUNTS VALUES (5674, 'Diana', 'Diana@123#''REVIEWER');
INSERT INTO USER_ACCOUNTS VALUES (9217, 'Adam', 'Adam@123#','SUPPORT');
COMMIT;
